NotAnAdmin: Sie müssen ein Administrator sein um diese Seite anzusehen.

Menu: Menü
Login: Anmelden
Logout: Abmelden
NewEntry: Neuer Eintrag
Categories: Kategorien
Uploads: Dateien
Users: Benutzer

BlogTitle: Blog
NoEntries: Es gibt leider keinen Eintrag.
NoCategoryEntries name@Text: Es gibt leider keine Einträge in der Kategorie #{name}.
ReadMoreEntry: Weiterlesen
NumberOfComments n@Int: #{show n} #{plural n "Kommentar" "Kommentare"}
FirstToComment: Geben Sie einen ersten Kommentar ab!
CategoryTitle blog@Text category@Text: #{blog}: Kategorie #{category}

EntryTitle blog@Text title@Text: #{blog}: #{title}
EditEntry: Bearbeiten
DeleteEntry: Löschen
DeleteComment: Löschen
CommentsHeading: Kommentare
NoComments: Es gibt noch keinen Kommentar.
AddCommentHeading: Kommentar abgeben
LoginToComment: Sie müssen angemeldet sein, um einen Kommentar abzugeben.
AddCommentButton: Kommantar abgeben

SaveEntryChanges: Änderungen speichern
NewEntryTitle: Titel
EditEntryTitle: Eintrag bearbeiten
NewEntrySummary: Zusammenfassung
NewEntryContent: Inhalt
NewEntryCategories: Kategorien
NewEntryTitleImage: Titelbild
NewEntryImages: Bilder
PreviewButton: Vorschau
JustPreviewWarning: Dies ist nur eine Vorschau!
SummaryTooLong length@Int: Die Zusammenfassung ist zu lang. Es sind nur #{show length} Zeichen erlaubt.

PleaseCorrectEntry: Der Eingegeben Beitrag hatte folgende Fehler:
PleaseCorrectEntryTitle: Bitte den Beitrag korrigieren
FormMissing: Formulardaten fehlen. Bitte erneut versuchen.
FormMissingTitle: Formulardaten fehlen.
EntryCreated title@Text: Ihr neuer Eintrag, #{title}, wurde erstellt.
EntryEdited title@Text: Ihr Eintrag, #{title}, wurde aktualisiert.

ReallyDeleteEntryTitle: Möchten Sie wirklich diesen Eintrag löschen?
ReallyDeleteEntry: Möchten Sie wirklich diesen Eintrag löschen?
ReallyDeleteSubmit: Löschen
EntryDeleted: Eintrag wurde gelöscht.

AdminAndAuthorAuthorizedDeleteComment: Nur ein Adminintrator oder der Autor des Kommentars, können diesen Kommentar löschen.
ReallyDeleteComment: Möchten Sie wirklich den folgenden Kommentar löschen?
ReallyDeleteCommentTitle: Möchten Sie wirklich den Kommntar löschen?
CommentDeleted: Der Kommantar wurde gelöscht.
CommentNotDeleted: Der Kommentar wurde nicht gelöscht.

CommentName: Ihr Anzeigename
CommentText: Kommentar
CommentAdded: Ihr Kommtar wurde gespeichert
PleaseCorrectComment: Ihr eingebener Kommentar hatte Fehler. Bitte korrigieren Sie diese und versuchen Sie es erneut.
CommentsDisabled: Kommentare sind deaktiviert.

CategoriesHeader: Kategorien
AddCategoryHeader: Kategorie hinzufügen
NoCategories: Es gibt noch keine Kategorien.
CategoriesTitle: Kategorien
NewCategoryName: Name der Kategorie
NewCategorySubmit: Kategorie hinzufügen
CategoryAdded name@Text: Kategorie #{name} wurde hinzugefügt.
CategoryAddFailed: Kategorie hinzufügen ist fehlgeschlagen.
DeleteCategory: Löschen
EditCategory: Bearbeiten

ReallyDeleteCategory name@Text: Möchten Sie wirklich die Kategorie #{name} löschen?
ReallyDeleteCategoryTitle name@Text: Lösche Kategorie #{name}
CategoryDeleted name@Text: Kategorie #{name} wurde gelöscht.
CategoryNotDeleted name@Text: Das Löschen der Kategorie #{name} ist fehlgeschlagen.

EditCategoryHeader: Kategorie bearbeiten.
EditCategorySubmit: Speichern
EditCategoryTitle name@Text: Kategorie #{name} bearbeiten
CategoryEdited name@Text: Kategorie #{name} wurde erfolgreich bearbeitet.
PleaseCorrectCategory: Ihr eingebene Kategorie hatte Fehler. Bitte korrigieren Sie diese und versuchen Sie es erneut.

UsersTitle: Benutzer
UsersHeader: Benutzer
NoUsers: Es gibt noch keine Benutzer.
EditUser: Bearbeiten

EditUserSubmit: Benutzer speichern
EditUserTitle ident@Text: Benutzer #{ident} bearbeiten
EditUserHeader ident@Text: Benutzer #{ident} bearbeiten
UserEdited ident@Text: Benutzer #{ident} wurde erfolgreich bearbeitet.
PleaseCorrectUser: Ihr eingegebener Benutzer hatte Fehler. Bitte korrigieren Sie diese und versuchen Sie es erneut.
IsAdmin: Administrator

UploadsTitle pagename@Text: pagename: Dateien
NoUploads: Es gibt noch keine hochgeladenen Dateien
NewUpload: Datei hochladen

NewUploadTitle: Neue Datei hochladen
UploadFileDescription: Beschreibung
UploadFileField: Datei
UploadFileSubmit: Hochladen
FileUploadFailed: Hochladen fehlgeschlagen.
UploadSaved: Hochladen erfolgreich.