NotAnAdmin: You must be an administrator to access this page.

Menu: Menu
Login: Login
Logout: Logout
NewEntry: New Entry
Categories: Categories
Users: Users

BlogTitle: Blog
NoEntries: There are no entries in the blog.
NoCategoryEntries name@Text: There are no entries in the category #{name}.
ReadMoreEntry: Read more
NumberOfComments n@Int: #{show n} #{plural n "comment" "comments"}
FirstToComment: Be the first to comment!
CategoryTitle blog@Text category@Text: #{blog}: category #{category}

EntryTitle blog@Text title@Text: #{blog}: #{title}
EditEntry: Edit
DeleteEntry: Delete
DeleteComment: Delete
CommentsHeading: Comments
NoComments: There are no comments.
AddCommentHeading: Add a Comment
LoginToComment: You must be logged in to comment.
AddCommentButton: Add comment

SaveEntryChanges: Save Changes
NewEntryTitle: Title
EditEntryTitle: Edit Entry
NewEntryContent: Content
NewEntryCategories: Categories
PreviewButton: Preview
JustPreviewWarning: This is just a preview!

PleaseCorrectEntry: Your submitted entry had some errors, please correct and try again.
EntryCreated title@Text: Your new blog post, #{title}, has been created.
EntryEdited title@Text: Your blog post, #{title}, has been updated.

ReallyDeleteEntryTitle: Do you really want to delete this entry?
ReallyDeleteEntry: Do you really want to delete the following entry?
ReallyDeleteSubmit: Delete
EntryDeleted: Blog post has been deleted.

AdminAndAuthorAuthorizedDeleteComment: Only the admin and the author of the comment are allowed to delete this comment.
ReallyDeleteComment: Do you really want to delete the following comment?
ReallyDeleteCommentTitle: Do you really want to delete this comment?
CommentDeleted: Comment has been deleted.
CommentNotDeleted: Comment has not been deleted.

CommentName: Your display name
CommentText: Comment
CommentAdded: Your comment has been added
PleaseCorrectComment: Your submitted comment had some errors, please correct and try again.
CommentsDisabled: Comments are disabled.

CategoriesHeader: Categories
AddCategoryHeader: Add Category
NoCategories: There are no categories yet.
CategoriesTitle: Categories
NewCategoryName: Category Name
NewCategorySubmit: Add Category
CategoryAdded name@Text: Added category #{name}
CategoryAddFailed: Adding category failed
DeleteCategory: Delete
EditCategory: Edit

ReallyDeleteCategory name@Text: Do you really want to delete the category #{name}?
ReallyDeleteCategoryTitle name@Text: Delete category #{name}
CategoryDeleted name@Text: Deleted category #{name}
CategoryNotDeleted name@Text: Deleting category #{name} failed

EditCategoryHeader: Edit Category
EditCategorySubmit: Save
EditCategoryTitle name@Text: Edit category #{name}
CategoryEdited name@Text: Category #{name} successfully edited
PleaseCorrectCategory: Your submitted category had some errors, please correct and try again.

UsersTitle: Users
NoUsers: There are no users, yet.
UsersHeader: Users
EditUser: Bearbeiten

EditUserSubmit: Save User
EditUserTitle ident@Text: Edit User #{ident}
EditUserHeader ident@Text: Edit User #{ident}
UserEdited ident@Text: User #{ident} successfully edited
PleaseCorrectUser: Your submitted user had some errors, please correct and try again.
IsAdmin: Admin
