NotAnAdmin: You must be an administrator to access this page.

HomepageTitle: Yesod Blog
Menu: Menu
Login: Login
Logout: Logout
NewEntry: New Entry

BlogTitle: Blog
NoEntries: There are no entries in the blog.
ReadMoreEntry: Read more
NumberOfComments n@Int: #{show n} #{plural n "comment" "comments"}
FirstToComment: Be the first to comment!

EntryTitle title@Text: Blog post: #{title}
EditEntry: Edit
DeleteEntry: Delete
CommentsHeading: Comments
NoComments: There are no comments.
AddCommentHeading: Add a Comment
LoginToComment: You must be logged in to comment.
AddCommentButton: Add comment

SaveEntryChanges: Save Changes
NewEntryTitle: Title
EditEntryTitle: Edit Entry
NewEntryContent: Content

PleaseCorrectEntry: Your submitted entry had some errors, please correct and try again.
EntryCreated title@Text: Your new blog post, #{title}, has been created.
EntryEdited title@Text: Your blog post, #{title}, has been updated.

ReallyDeleteEntryTitle: Do you really want to delete?
ReallyDeleteEntry: Do you really want to delete the following entry?
ReallyDeleteSubmit: Delete
EntryDeleted: Blog post has been deleted.

CommentName: Your display name
CommentText: Comment
CommentAdded: Your comment has been added
PleaseCorrectComment: Your submitted comment had some errors, please correct and try again.


